version: '2'
services:
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
        ports:
            - "9200:9200"
        expose:
            - 9200
        restart: unless-stopped
        environment:
            - "transport.host=127.0.0.1"
            - "xpack.security.enabled=false"
        volumes:
            - "./elasticsearch/data/:/usr/share/elasticsearch/data"

    redis:
      image: redis:3
      volumes:
        - ./redis/data:/var/lib/redis
      ports:
        - "6379:6379"
      restart: always

    logstash:
        container_name: logstash
        image: logstash:5.5.1
        command: logstash -f /etc/logstash/conf.d/logstash.conf
        volumes:
          - ./logstash/config:/etc/logstash/conf.d
        ports:
          - "5000:5000"
        links:
          - redis
          - elasticsearch
        restart: always

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:5.5.1
        restart: unless-stopped
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        environment:
            - "ELASTICSEARCH_URL: http://elasticsearch:9200"
        expose:
            - 5601
        volumes:
            - ./kibana/config/:/opt/kibana/config/